
# You do not need the baseurl in your configuration file.
baseurl: /building_a_static_website_part_1

timezone: Australia/Brisbane

collections:
  projects:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jane Bloggs"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"